### ISSUE TITLE
Get `TypeError: can't pickle _thread._local objects` in running AllReduce Strategy

### ISSUE THREAD

**Issue by AmberCheng** [tensorflow/ecosystem#103]
Hi,

I just follow your instruction to run the standalone AllReduce Example. But I got this error-'TypeError: can't pickle _thread._local objects'
  
 
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:MocOS 10.13.6 (17G65)
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**:None
- **TensorFlow installed from (source or binary)**: Anaconda
- **TensorFlow version (use command below)**: 1.11
- **Python version**:3.6.5
- **Exact command to reproduce**:
```
export TF_CONFIG='{"cluster":{"worker":["localhost:10000", "localhost:10001"],"chief":["localhost:10002"]}, "task":{"type":"worker","index":0}}'
python tf_std_server.py

export TF_CONFIG='{"cluster":{"worker":["localhost:10000", "localhost:10001"],"chief":["localhost:10002"]}, "task":{"type":"worker","index":1}}'
python tf_std_server.py

export TF_CONFIG='{"cluster":{"worker":["localhost:10000", "localhost:10001"],"chief":["localhost:10002"]}, "task":{"type":"chief","index":0}}'
python tf_std_server.py

export TF_CLUSTER='{"worker":["localhost:10000", "localhost:10001"],"chief":["localhost:10002"]}'
python keras_model_to_estimator_client_alt.py /tmp/checkpoints
```
### Describe the problem
I just follow the[ instruction](https://github.com/tensorflow/ecosystem/blob/65299036e6f64e3d333fafd437624a6f8bb0bea6/distribution_strategy/README.md) to run the example standalone-CollectiveAllReduce code on my computer , but I still  get the error -  'TypeError: can't pickle _thread._local objects'

### Source code
https://github.com/tensorflow/ecosystem/blob/65299036e6f64e3d333fafd437624a6f8bb0bea6/distribution_strategy/tf_std_server.py  
https://github.com/tensorflow/ecosystem/blob/65299036e6f64e3d333fafd437624a6f8bb0bea6/distribution_strategy/tf_std_server.py

**Comment by AmberCheng** [comment]
@dmitrievanthony Hi, I find that you have distributed this part, can you solve my problem? Thank you very much ^^~~~

**Comment by byronyi** [comment]
It’s fixed in current master. Update your TF to nightly.

**Comment by AmberCheng** [comment]
> It’s fixed in current master. Update your TF to nightly.

I have used latest TF1.11, which is released. Does it have this problem unfixed?

**Comment by byronyi** [comment]
Try tf-nightly-gpu instead.

**Comment by AmberCheng** [comment]
> Try tf-nightly-gpu instead.

I don't think Mac OS can support tf-nightly-gpu. I found that Mac can only support the CPU-only ones.

**Comment by byronyi** [comment]
Then use tf-nightly instead.
