### ISSUE TITLE
[TFRecords File is too large] 3 times than parquet, 1.3 times than normal textFile

### ISSUE THREAD

**Issue by Zachary4biz** [tensorflow/ecosystem#106]
**As  a binary file, shouldn't TFRecords-file be much smaller than other types of file?(especially some textFile of RDD)**

I have created this "featureDF", and saved it in 3 different ways.  
parquet: **793.4M**
`featureDF.write.parquet("xxx")`
textFile: **1.8G**
`featureDF.rdd.saveAsTextFile("xxxx")`
tfrecords: **2.4G**
`featureDF.write.format("tfrecords").options("recordType","Example").save("xxx")`

and with tfrecords, `options("codec","org.apache.hadoop.io.compress.GzipCodec")` is not working.
so i tried the linux command `gzip -9 featureDF.tfrecord`, compressed it from 2.4G to 515M, cost 5 min. But the `gzip -9 featureDF.parquet` compressed a parquet file from 793.4M to 149M.

Is there any efficient way to compress this tfrecord files?
(already tried replace DoubleType and LongTpye with StringType,  not useful)

**Comment by bigbear2017** [comment]
you can compress tfrecord output using gzip. refer to this pull request:
https://github.com/tensorflow/ecosystem/pull/108

**Comment by Zachary4biz** [comment]
> you can compress tfrecord output using gzip. refer to this pull request:
> #108

Glad to see your PR! @bigbear2017 
Currently I just merge the command `gzip -c ...` into the program, and it works fine. I will try your fix!

**Comment by qiaoguan** [comment]
Execuse me,  i user spark to transform the original format to TFrecord format,  it works ,  but the tfrecord file is too large ,  i want to compress it,     what should i do?

import org.tensorflow.hadoop.io.TFRecordFileOutputFormat
import org.tensorflow.hadoop.shaded.protobuf.ByteString
import org.apache.hadoop.io.compress.CompressionCodec
import org.apache.hadoop.io.compress.GzipCodec

val tfrecord_sample_dir = sample_dir + localArgs.yyyyMMdd + "/" + localArgs.loc+"_tfrecord"
    FileSystem.get(sc.hadoopConfiguration).delete(new Path(tfrecord_sample_dir), true)
    tfrecord_sample.saveAsNewAPIHadoopFile[TFRecordFileOutputFormat](tfrecord_sample_dir)

where tfrecord_sample is a RDD[(BytesWritable, NullWriteable)] format,   BytesWritable is a tfrecord example format。 i see saveAsHadoopFile function provide a way to compress the original data,  but i do not know how to use it,  anyone can help?
/**
   * Output the RDD to any Hadoop-supported file system, using a Hadoop `OutputFormat` class
   * supporting the key and value types K and V in this RDD. Compress the result with the
   * supplied codec.
   */
  def saveAsHadoopFile[F <: OutputFormat[K, V]](
      path: String,
      codec: Class[_ <: CompressionCodec])(implicit fm: ClassTag[F]): Unit = self.withScope {
    val runtimeClass = fm.runtimeClass
    saveAsHadoopFile(path, keyClass, valueClass, runtimeClass.asInstanceOf[Class[F]], codec)
  }

i try to use 
  tfrecord_sample.saveAsHadoopFile[TFRecordFileOutputFormat](tfrecord_sample_dir, GzipCodec)
like this ,  but it doesn't work

**Comment by Zachary4biz** [comment]
um. maybe you should format your code with standard markdown style, it's a bit messy.

Officially : **you can check the #108  issue**. since they have merged PR #125, there should be an official support for gzip compress in some latest version after March.

Personally: seems u are using scala, compress data by bash command is worth trying:
`Seq("sh","-c",s"gzip -c -9 your_data_dir/part-* > target_dir/train.tfrecord.gz").!`
