### ISSUE TITLE
Complete Example TFRecord generated using Spark on Tensorflow training 

### ISSUE THREAD

**Issue by asheeshgarg** [tensorflow/ecosystem#124]
I am trying to use Spark preprocessing to generate TFRecords to hdfs and use the data generated on hdfs to use in training a Tensorflow model. I don't find any example where the data generated using spark process to be consumed and trained using distributed Tensorflow.

I am able to use spark to create dataframe out of the data stored using TF records but not sure how to pass the dataframe as input to TFRecord or even using the data generated in HDFS a complete example will help quick start.

**Comment by manuzhang** [comment]
Take a look at https://github.com/tensorflow/models/blob/master/official/wide_deep/movielens_dataset.py

**Comment by asheeshgarg** [comment]
Here is a simple example I am trying not able to get second the second value parsed

simpleSchema = StructType([StructField("id", IntegerType()),StructField("value", StringType())])
simple_rows = [[11, "r1"],[21, "r2"]]
rdd = localspark.sparkContext.parallelize(simple_rows)
df = localspark.createDataFrame(rdd, simpleSchema)
df.write.format("tfrecords").mode('overwrite').option("recordType", "Example").save("test1")

importedDf = localspark.read.format("tfrecords").option("recordType", "Example").schema(simpleSchema).load("test1")
importedDf.show()

This is the output I get
+---+-----+
| id|value|
+---+-----+
| 11|   r1|
| 21|   r2|
+---+-----+

Now when tried to read back using Dataset

def parse_single(example):
    parsed = tf.parse_single_example(example, features={
        'id': tf.FixedLenFeature([1], dtype=tf.int64),
        'data': tf.FixedLenSequenceFeature([], dtype=tf.string,allow_missing=True)
    })
    return parsed['id'],parsed['data']

filenames = tf.gfile.Glob('hdfs://DOB2-GEN/user/agarg86/test1/*')
dataset   = tf.data.TFRecordDataset(filenames)
dataset   = dataset.map(parse_single)
dataset   = dataset.batch(1)
iterator  = dataset.make_one_shot_iterator()
for x,y in iterator:
    print(x)
    print(y)
  
**Not able to get second value r1,r2 read**
tf.Tensor([[11]], shape=(1, 1), dtype=int64)
tf.Tensor([], shape=(1, 0), dtype=string)
tf.Tensor([[21]], shape=(1, 1), dtype=int64)
tf.Tensor([], shape=(1, 0), dtype=string)

**Comment by asheeshgarg** [comment]
Able to figure out the issue was reading the parsed example using different column name. Once I renamed data to value the data showed up fine.
