### ISSUE TITLE
problem: with this   tf.train.MonitoredTrainingSession

### ISSUE THREAD

**Issue by tbchj** [tensorflow/ecosystem#26]
i build a new dockerimage by your dockerfile , but when i run  mnist.py on k8s cluster, it occurs  no moudle:
tf.train.MonitoredTrainingSession.
the tensorflow version is 0.9 , why ? how to solve the problem?

**Comment by jhseu** [comment]
MonitoredTrainingSession is only in TensorFlow version 0.12 or later. You can rework the example to not use it if you want to use an earlier version of TensorFlow.

**Comment by tbchj** [comment]
@jhseu    ok,thank you.
