### ISSUE TITLE
TensorFlow implementation in MapReduce

### ISSUE THREAD

**Issue by rendi7936** [tensorflow/ecosystem#27]
Hello guys,

I just want to ask something. Can i implement TensorFlow in MapReduce Programming Model within Hadoop ?

Yes, i know that TensorFlow can be runned in distributed mode, according this reference https://www.tensorflow.org/versions/r0.11/how_tos/distributed/ . But, it doesn't explain more detail how to use it in MapReduce.

I see **Apache Hadoop MapReduce InputFormat/OutputFormat implementation for TensorFlow's TFRecords format** in this repo. But, i dont have any idea about this. Can you explain to me, what is it ? And what is it for ? Can i use it to help for writing TensorFlow in MapReduce way ?

One last thing, can i use TensorFlow to predict something a lot of data ? Because, i only know that TensorFlow can be used to classify similar images.

I'm sorry if my question look dumb. Well, there are many thing in the world that i don't know. So, when i don't know, i will ask a question :smile: 
Thanks for your attention

**Comment by jhseu** [comment]
Yes, TensorFlow can be used with Hadoop. We have experimental Java bindings that can be used: https://github.com/tensorflow/tensorflow/tree/master/tensorflow/java

It's primarily useful for inference. For training, we'd recommend you do that outside of Hadoop.
