### ISSUE TITLE
Add tensorflow-hadoop jar to public maven repository

### ISSUE THREAD

**Issue by skavulya** [tensorflow/ecosystem#29]
Feature request to add versioned tensorflow-hadoop jars to a public maven repository. This will make it easier to develop Java libraries that rely on it. Currently, we need to compile our own snapshot versions of the library to use it.

**Comment by tonye0115** [comment]
Can you provide a public maven repository, can dependency on tensorflow-hadoop.jar, thanks

**Comment by damnMeddlingKid** [comment]
This project could be added to the OSSRH http://central.sonatype.org/pages/ossrh-guide.html I can own this if no one has time to figure it out ?.

**Comment by kailuowang** [comment]
Can we add the spark connector too as well?

**Comment by devarti** [comment]
Hello:
Do we have those two jars available for download from any location? thanks

**Comment by skavulya** [comment]
@devarti We don't have the jars publicly available for download so you need to build them. There is a snapshot version of tensorflow-hadoop that the tensorflow-spark connector in its Maven pom, but no official versions of the jars.

@jhseu would it be possible to host the tensorflow-hadoop and the tensorflow-spark-connector jars under Google's org.tensorflow namespace on Maven central?

**Comment by jhseu** [comment]
@skavulya Yeah, if you have time, could you add the scripts to upload it here and send a pull request?
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/java/maven

See the README and release.sh for instructions. Once added, it'll be updated upon every TensorFlow release. You can just have the script git clone this repository.

**Comment by skavulya** [comment]
@jhseu sure, I'll work on it over the weekend. I took a quick glance at the repo, it looks like I need to add a script to tools/ci_build then download the jars in https://github.com/tensorflow/tensorflow/blob/master/tensorflow/java/maven/run_inside_container.sh. 

Is this the procedure you would like me to follow, or should I add a function to git clone, build and run tests directly in run_inside_container.sh?

**Comment by jhseu** [comment]
It should be fine to git clone, build, and run tests directly in run_inside_container.sh. Whichever is easier.

**Comment by skavulya** [comment]
@jhseu It will be easier to run the build directly in run_inside_container.sh. I'll work on generating the jars for both Hadoop and Spark.

**Comment by kevinykuo** [comment]
What would it take to get the `spark-tensorflow-connector` artifact on Central? Currently it's only available from a lesser known repository (see https://mvnrepository.com/artifact/org.tensorflow/spark-tensorflow-connector) and we're concerned it might not be stable enough for downstream users.

**Comment by skavulya** [comment]
@kevinykuo I'm working on this. Should have the PR done this week.

**Comment by kevinykuo** [comment]
@skavulya I see the PR has been merged upstream; do we know when this will be available via Maven? Is it dependent on a new version release in tensorflow?

**Comment by skavulya** [comment]
@kevinykuo I am not sure if the PR was merged in time to make it into the 1.9.0 release. @jhseu would know.

**Comment by jhseu** [comment]
As far as I can tell, it should be pushed out with the 1.9.0 final release.

**Comment by skavulya** [comment]
Thanks @jhseu
