### ISSUE TITLE
Add support for SequenceExample to Spark TensorFlow Connector

### ISSUE THREAD

**Issue by skavulya** [tensorflow/ecosystem#36]
We received a request from @mpekalski  to add support for feature lists specified in the SequenceExample tfrecord. At present, the connector only supports Example messages.

We are proposing that each feature_list gets represented as an Array of Arrays of type Long, Float or String depending on whether it is an Int64List, FloatList, or ByteList.

For example, a Spark SQL row of: 
```
StructType(List(
    StructField("movie_ratings", ArrayType(ArrayType(LongType, true), true)), 
    StructField("actors", ArrayType(ArrayType(StringType, true), true)))
))
```

gets represented as a SequenceExample with feature_lists:
```
feature_lists: { 
  feature_list: {
      key: "movie_ratings"
      value: { feature: { int64_list: { value: [ 4 ] } }
               feature: { int64_list: { value: [ 5 ] } }
               feature: { int64_list: { value: [ 2 ] } } }
     } 
  }
  feature_list: {
      key  : "actors"
      value: { feature: {  bytes_list: { value: [ "Tim Robbins", "Morgan Freeman" ]} }         
            feature: { bytes_list: { value: [ "Brad Pitt", "Edward Norton", "Helena Bonham Carter" ] } }
      }
  }
}
```

@jhseu, @mpekalski, @karthikvadla, @joyeshmishra, please let us know if you would like us to make any changes to the proposed API. We will work on the pull request.

**Comment by jhseu** [comment]
Seems reasonable to me.

**Comment by skavulya** [comment]
@mpekalski You can try out the youtube-8m example using a custom schema here https://github.com/skavulya/ecosystem/tree/spark-tf-sequence-example/spark/spark-tensorflow-connector The README includes an example of how to read the video and frame datasets

We are wrapping up the schema inference piece, and we will submit the pull request for review soon.

**Comment by mpekalski** [comment]
Great, I will give it a try.

**Comment by skavulya** [comment]
I created the PR for this issue https://github.com/tensorflow/ecosystem/pull/52. Sorry for the delay.
