### ISSUE TITLE
Hadoop: reading TFRecords from TensorFlow fails

### ISSUE THREAD

**Issue by bzz** [tensorflow/ecosystem#47]
Hi, I'm using `tensorflow-hadoop` to save some data from Apache Spark and then read it on TensorFlow side as [TFRecords](https://www.tensorflow.org/api_guides/python/python_io#tfrecords_format_details).

Although resulting files can be read using `tf.python_io.tf_record_iterator()`, I can not find the way to make it work with queues and  [tf.TFRecordReader with the tf.parse_single_example decoder](https://www.tensorflow.org/programmers_guide/reading_data#standard_tensorflow_format)

Here is simplest reproducible example:
 
 - `mvn surefire:test -Dtest=TFRecordFileTest` to get TFRecords `tmp/tfr-test/part-m-00000`
 - `protoc --decode_raw < /tmp/tfr-test/part-m-00000` and get `Failed to parse input.` (why?)
 -  reading with [tf.python_io.tf_record_iterator()](https://www.tensorflow.org/api_docs/python/tf/python_io/tf_record_iterator) **works**

    ```python
    tfrecord = "/tmp/tfr-test/part-m-00001"
    for serialized_example in tf.python_io.tf_record_iterator(tfrecord):
      example = tf.train.Example()
      example.ParseFromString(serialized_example)
      rec = example.features.feature['data'].int64_list.value
      print(rec)
    ```

    Prints the list of int values, as expected.

  - reading with [tf.parse_single_example()](https://www.tensorflow.org/api_docs/python/tf/parse_single_example) **fails**

    ```python
    filenames = glob.glob("/tmp/tfr-test/part-m-0000*")
    filename_queue = tf.train.string_input_producer(filenames)
    reader = tf.WholeFileReader()
    _, serialized_example = reader.read(filename_queue)
    features = tf.parse_single_example(
        serialized_example,
        features={'data': tf.VarLenFeature(dtype=tf.int64)})
    
    data = features['data'].values
    
    sess = tf.InteractiveSession()
    tf.train.start_queue_runners(sess=sess)
    print(data.eval())
    ```

    with `InvalidArgumentError: Could not parse example input, value: '`

    <details>

    ```
    >>> print(data.eval())
    2017-05-26 20:05:17.917177: W tensorflow/core/framework/op_kernel.cc:1152] Invalid argument: Could not parse example input, value: '
         Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/<python>//lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 569, in eval
        return _eval_using_default_session(self, feed_dict, self.graph, session)
      File "/<python>//lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3741, in _eval_using_default_session
        return session.run(tensors, feed_dict)
      File "/<python>//lib/python2.7/site-packages/tensorflow/python/client/session.py", line 778, in run
        run_metadata_ptr)
      File "/<python>//lib/python2.7/site-packages/tensorflow/python/client/session.py", line 982, in _run
        feed_dict_string, options, run_metadata)
      File "/<python>//lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1032, in _do_run
        target_list, options, run_metadata)
      File "/<python>//lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1052, in _do_call
        raise type(e)(node_def, op, message)
    tensorflow.python.framework.errors_impl.InvalidArgumentError: Could not parse example input, value: '
    ```
    </details>

Did I miss something or is that an expected result? Would appreciate any help here.

**Comment by bzz** [comment]
@llhe did you experience any similar issues \w reading `TFRecordFileOutputFormat` from TensorFlow or am I doing something wrong?

**Comment by llhe** [comment]
@bzz The generated TFRecord file contains a sequence of records like this:
```
uint64 length
uint32 masked_crc32_of_length
byte   data[length]
uint32 masked_crc32_of_data
```
Where the `data` is pb serialized `Example`.

So both `protoc --decode_raw < /tmp/tfr-test/part-m-00000` and `tf.WholeFileReader()` will fail. You should change `tf.WholeFileReader` to `tf.TFRecordReader`.

**Comment by bzz** [comment]
Thank you very much @llhe for pointing it out, have overlooked it into [TF docs: Inputs and Readers > Readers](https://www.tensorflow.org/api_guides/python/io_ops#Readers)

Indeed, [TFRecord format](https://www.tensorflow.org/api_guides/python/python_io#tfrecords_format_details) is documented, and one can see [TFRecordWriter.java](https://github.com/tensorflow/ecosystem/blob/master/hadoop/src/main/java/org/tensorflow/hadoop/util/TFRecordWriter.java) implementing it.
