### ISSUE TITLE
tensorflow-hadoop fails to compile with protoc 3.3.0

### ISSUE THREAD

**Issue by rishihahs** [tensorflow/ecosystem#48]
The newest protoc (3.3.0) causes a compilation failure with errors such as:

    ... hadoop/src/main/java/org/tensorflow/example/FloatList.java:[194,17] error: no suitable method found for parseFrom(ByteBuffer)
    [ERROR] int,int) is not applicable

Compiling with protoc 3.1.0 (as per the README) works fine.

**Comment by skavulya** [comment]
Try:
```
mvn clean package -Dprotobuf.version=3.3.1 
```
