### ISSUE TITLE
feature decoder issue of Spark tensorflow connector

### ISSUE THREAD

**Issue by lutianming** [tensorflow/ecosystem#51]
Right now, the `StringFeatureDecoder` uses the following logic to transform bytesList to String

`feature.getBytesList.toByteString.toStringUtf8.trim `

Since BytesList is a `List[ByteString]`, this might work if bytesList only contains one string. But when there is a binary image or multiple strings, it will not work any more.

I think it might be better to map BytesList to Array[Array[Byte] instead of String, and let users decide if they need to convert Array[Byte] to string after getting the dataset.

**Comment by skavulya** [comment]
I created a PR which should address this issue. Please let me know if the issue still persists after the PR is merged https://github.com/tensorflow/ecosystem/pull/52
