### ISSUE TITLE
spark-tensorflow-connector support for BinaryType

### ISSUE THREAD

**Issue by neggert** [tensorflow/ecosystem#60]
I'm working on a project where I'm trying to store binary data (jpeg-encoded images). They're currently stored in a Spark-sql `BinaryType` column, and I'm want to them to end up in a `BytesList` field in my tfrecords.

Considering I'm trying to copy binary data byte-by-byte, this has proven surprisingly difficult, mainly because I have to convert to String in between, which introduces all sorts of issues with character encodings. This would be much easier if we could go directly to and from `BinaryType`.

I'm willing to contribute a PR, but I wanted to get some eyes on a proposal before I spend time writing code. I'd like to add an encoder that will go directly from a `BinaryType` column to `BytesList`. I think this is relatively uncontroversial.

The second bit is trickier. What should happen when we read a `BytesList` from TFRecords?. Right now, I think it's assumed to be a UTF-8-encoded string and is decoded as such. I'm guessing this actually covers the majority of use cases, it might cause problems if a user actually wants their binary data back (haven't actually tested this). It seems like a more natural approach would be to return a `BinaryType` and let the user cast to `StringType` if that's what they want. This, of course, would break existing code, so maybe it's a non-starter.

Thoughts? My immediate concern is just the encoder, but I thought I'd raise the other issue as well for consistency's sake.

**Comment by skavulya** [comment]
@neggert Thanks for your contribution! I'll take a look at it.

**Comment by neggert** [comment]
Thanks! Working on getting the CLA signed. Apparently someone else already started this ball rolling, so hopefully it won't take too long.
