### ISSUE TITLE
Spark Package for spark-tensorflow-connector

### ISSUE THREAD

**Issue by sueann** [tensorflow/ecosystem#62]
Hi, 
I found the Spark Package for spark-tensorflow-connector at https://spark-packages.org/package/tapanalyticstoolkit/spark-tensorflow-connector. Is that a stable version to use, or would you recommend building from master here? Do you plan to update the Spark Package regularly?

Thanks,
Sue Ann

**Comment by skavulya** [comment]
@sueann I would recommend building from master here because the package on spark-packages is outdated. We are still working on the logistics of switching the packaging to this repo.

**Comment by sueann** [comment]
got it. thanks!
