### ISSUE TITLE
run distributed training with kubernetes: worker wait for ps reponse forever

### ISSUE THREAD

**Issue by scotthuang1989** [tensorflow/ecosystem#64]
I am new to distributed world. I setup a kubernete cluster with 2 node. then I run the example with 1 ps and 1 worker. but my worker seems wait forever.

here is my log from worker pod: kubectl logs mymnistdist-worker-0-6b11q
> 2017-09-05 02:06:37.768560: I tensorflow/core/distributed_runtime/master.cc:221] CreateSession still waiting for response from worker: /job:ps/replica:0/task:0

here my my log from ps pod: 

> 01:42:57.575306: I tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc:324] Started server with target: grpc://localhost:5000

Ｉ login into these 2 pods, found out that the hostname is:

> mymnistdist-ps-0-ncfjz
> mymnistdist-worker-0-6b11q

they have a random suffix. but what I give  to the tf.train.ClusterSpec is : 

>      worker_hosts=mymnistdist-worker-0:5000
       

>     ps_hosts=mymnistdist-ps-0:5000

I google around, seems there is no way to set a pod name in a kubernete ReplicaSet. 
Is there a way to work around this?

**Comment by scotthuang1989** [comment]
ok. I think the example workaround the host name issue with a kubernete service.  I

**Comment by limjoe** [comment]
I have the same problem.

**Comment by scotthuang1989** [comment]
@limjoe  I figured it out. This is a problem of "pod network" . you can check this  [link](https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/) to find out more. I choose Calico as my pod network. but it don't work well on my system(ubuntu 16.04), actually the Calico official document also said that it requires some manual configuration on ubuntu. So I switch to Canal . Then it works well.

**Comment by limjoe** [comment]
Thanks a lot, I used flannel network add-on before. And Canal works well indeed.

**Comment by LynnaPan** [comment]
hi, I encountered the same problem:
```
2017-10-20 05:03:41.425370: I tensorflow/core/distributed_runtime/master.cc:209] CreateSession still waiting for response from worker: /job:ps/replica:0/task:0 

2017-10-20 05:03:41.425421: I tensorflow/core/distributed_runtime/master.cc:209] CreateSession still waiting for response from worker: /job:worker/replica:0/task:0
```

Also I switch network to canal, the problem still there.
Is there any way to troubleshooting?
