### ISSUE TITLE
Error with Maven3 Build in Ubuntu 14.04

### ISSUE THREAD

**Issue by mohammedayub44** [tensorflow/ecosystem#72]
Hi,
I keep getting a  error when I do the build with maven 3.3.9:
"/ecosystem/hadoop/src/main/java/org/tensorflow/hadoop/example/TFRecordFileMRExample.java: package org.tensorflow.example does not exist" error. I have successfully downloaded and installed the prerequisites. Not sure if it a protobuf issue or a mvn issue.

**Comment by skavulya** [comment]
@mohammedayub44 This looks like it a protobuf issue. Check if you can see the Example protos in ecosystem/hadoop/src/main/java/org/tensorflow/example/

**Comment by ankitkaushik** [comment]
@mohammedayub44, I ran into the same issue as you and I am also using Ubuntu 14.04. I can find the file **TFRecordFileMRExample.java** under **ecosystem/hadoop/src/main/java/org/tensorflow/hadoop/example/**. I noticed on this page (https://www.tensorflow.org/versions/master/install/install_java) that Tensorflow for Java support only exists for Ubuntu 16.04 and higher, could this be the issue?

**Comment by ankitkaushik** [comment]
@skavulya, using the latest master fixed the problem! Thank you very much for this fix.

**Comment by skavulya** [comment]
Great! @jhseu This issue can be closed.
