### ISSUE TITLE
Compile the code failed.Class java.lang.FunctionalInterface not found

### ISSUE THREAD

**Issue by charmby** [tensorflow/ecosystem#82]
[ERROR] Class java.lang.FunctionalInterface not found - continuing with a stub.
[ERROR] Class java.lang.FunctionalInterface not found - continuing with a stub.
[ERROR] Class java.lang.FunctionalInterface not found - continuing with a stub.
[ERROR] Class java.lang.FunctionalInterface not found - continuing with a stub.
[ERROR] Class java.lang.FunctionalInterface not found - continuing with a stub.
[ERROR] Class java.lang.FunctionalInterface not found - continuing with a stub.
[ERROR] Class java.lang.FunctionalInterface not found - continuing with a stub.
[ERROR] 7 errors found

**Comment by skavulya** [comment]
@charmby  Glad you managed to resolve it :) Please close the issue
