### ISSUE TITLE
Failed to build on hadoop with maven3

### ISSUE THREAD

**Issue by mohammedayub44** [tensorflow/ecosystem#91]
I'm getting the following error while compiling the packages in ecosystem/hadoop for my tensorflowonspark test.  The error seems to be with maven-plugin - surefire plugin. 

I have the following version of maven installed on my Ubuntu 16.04:

`mayub@nf-qu-bd-h01:~/ecosystem/hadoop$ mvn -v`
`Apache Maven 3.3.9`
`Maven home: /usr/share/maven`
`Java version: 1.7.0_67, vendor: Oracle Corporation`
`Java home: /usr/lib/jvm/java-7-oracle-cloudera/jre`
`Default locale: en_US, platform encoding: UTF-8`
`OS name: "linux", version: "4.4.0-87-generic", arch: "amd64", family: "unix" `

Below is the error

`mayub@nf-qu-bd-h01:~/ecosystem/hadoop$ mvn -U clean install`
`[INFO] Scanning for projects...`
`[INFO]`
`[INFO] ------------------------------------------------------------------------`
`[INFO] Building tensorflow-hadoop 1.8.0`
`[INFO] ------------------------------------------------------------------------`
`Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-surefire-plugin/2.17/maven-surefire-plugin-2.17.pom`
`[INFO] ------------------------------------------------------------------------`
`[INFO] BUILD FAILURE`
`[INFO] ------------------------------------------------------------------------`
`[INFO] Total time: 1.958 s`
`[INFO] Finished at: 2018-06-28T20:41:30-04:00`
`[INFO] Final Memory: 27M/1963M`
`[INFO] ------------------------------------------------------------------------`
`[ERROR] Plugin org.apache.maven.plugins:maven-surefire-plugin:2.17 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-surefire-plugin:jar:2.17: Could not transfer artifact org.apache.maven.plugins:maven-surefire-plugin:pom:2.17 from/to central (https://repo.maven.apache.org/maven2): Received fatal alert: protocol_version -> [Help 1]`
`[ERROR]`
`[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.`
`[ERROR] Re-run Maven using the -X switch to enable full debug logging.`
`[ERROR]`
`[ERROR] For more information about the errors and possible solutions, please read the following articles:`
`[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException`

Any help is appreciated.

**Comment by skavulya** [comment]
@mohammedayub44 I am unable to reproduce the error you are observing with maven 3.3.9 and java 1.7/1.8. 

It looks like it might be a connection issue. Are you running the build behind a proxy?

**Comment by mohammedayub44** [comment]
@skavulya  I confirmed from my IT folks they said there is no proxy on the machines. How can I check that to be sure ?

Thanks.

**Comment by skavulya** [comment]
@mohammedayub44 I came across this thread that might help https://stackoverflow.com/questions/50824789/why-am-i-getting-received-fatal-alert-protocol-version-or-peer-not-authentic

**Comment by mohammedayub44** [comment]
@skavulya  Thanks a lot. This works like a charm. This was driving me crazy for two weeks.
I was able to generate the jar file specifying below command:
`mvn -Dhttps.protocols=TLSv1.2 clean install -X`
