### ISSUE TITLE
How to use tensorflow code to resovle tfrecords got from spark correctly ？

### ISSUE THREAD

**Issue by aixuedegege** [tensorflow/ecosystem#97]
I have some problems when I use “spark-tensorflow-connector”. And I can not solve it in a month, so I have no choice but to ask you for advice.
I want to get TFRecords from spark , so I use df.write.format("tfrecords").option("recordType", "Example").save(path). But when I resolve the TFRecords by tensorflow code,the data was wrong. For example, my data on spark is 

feature1,feature2
Hello, friend
HI   , girl

When I use tensorflow to resolve the result transformed by “spark-tensorflow-connector”,I got this:
feature1,feature2
Hello,  girl
HI   , friend 

The data was error.
So how can I resolve this problem ? 
I just use “df.coalesce(1).write.format("tfrecords")” to solve the problem.But this way is very slow.
I am sorry to disturb you during your busy schedule. Waiting for your reply. Thank you very much!

**Comment by skavulya** [comment]
Can you add a snippet of the TensorFlow code you are using to read the tfrecords?

**Comment by aixuedegege** [comment]
Thank you for your time！
Here is my core python codes:

tfrecordFiles = ['xxx/part-r-00000','xxx/part-r-00001'] 
#part-r-00000 is a tfrecord file downloaded from hdfs
reader = tf.TFRecordReader()
filename_queue = tf.train.string_input_producer(tfrecordFiles)
_, serialized_example = reader.read(filename_queue)
batch = tf.train.batch([serialized_example],batch_size=5)
feature = {
‘feature1’：tf.FixedLenFeature([])], tf.string)，
‘feature2’：tf.FixedLenFeature([])], tf.string)，
}
features = tf.parse_example(batch,features=feature) 
with tf.Session() as sess:
        init_op = tf.global_variables_initializer()
        sess.run(init_op)
        coord=tf.train.Coordinator()
        threads= tf.train.start_queue_runners(coord=coord)
        data = []
        for key in feature .keys():
            tmp = sess.run(features[key ])
            data.append(tmp)
#codes over 

But when i use the following code，I can get correct result.

data = []
for s_example in tf.python_io.tf_record_iterator('xxx/part-r-00000'):
    example = tf.train.Example()
    example.ParseFromString(s_example)
    result = [
            example.features.feature['feature1'].bytes_list.value[0],
            example.features.feature['feature2'].bytes_list.value[0],           
            ]                                
    data.append(result)

**Comment by skavulya** [comment]
@aixuedegege Try using the DataSet API https://www.tensorflow.org/guide/datasets 

For example,

```
def _parse_function(example_proto):
  features = {"feature1": tf.FixedLenFeature((), tf.string, default_value=""), "feature2": tf.FixedLenFeature((), tf.string, default_value="")}
  parsed_features = tf.parse_single_example(example_proto, features)
  return parsed_features["feature1"], parsed_features["feature2"]

filenames = ['xxx/part-r-00000','xxx/part-r-00001']
dataset = tf.data.TFRecordDataset(filenames)
dataset = dataset.map(_parse_function)

#print values
iterator = dataset.make_one_shot_iterator()
sess = tf.Session()
sess.run(next_element)
```

**Comment by aixuedegege** [comment]
Thank you very much！

**Comment by skavulya** [comment]
Glad it worked :) Please close the issue.
